-- 步骤4：启用行级安全
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE historical_figures ENABLE ROW LEVEL SECURITY;
ALTER TABLE cultural_heritage ENABLE ROW LEVEL SECURITY;
ALTER TABLE charity_projects ENABLE ROW LEVEL SECURITY;